export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_ERROR = 'SET_ERROR'
export const FETCH_USERS = 'FETCH_USERS'
export const REMOVE_USER = 'REMOVE_USER'
export const ADD_USER = 'ADD_USER'
